- hosts: namenode
  vars_prompt:
    - name: namedir
      prompt: "Enter Name Node Directory Name "
      private: no
    - name: nameip
      prompt: "Enter Name Node IP "
      private: no

  tasks:
    - name: "Copying the hadoop File"
      copy:
        src: "/root/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"
    - name: "Copying the JDK File"
      copy:
        src: "/root/jdk-8u171-linux-x64.rpm"
        dest: "/root/"
    - name: Installing Java Software
      command: "rpm -ivh jdk-8u171-linux-x64.rpm"
      register: java
    - debug:
        var: java.stdout  
    
    - name: Installing Hadoop Software
      command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
      register: hadoop
      when: java.rc == 0
    - debug:
        var: hadoop.stdout
     
 
    - name: Creating Name Node Directory
      file:
        path: "{{ namedir }}"
        state: directory


    - name: Configuring hdfs-site.xml
      blockinfile:
        path: /etc/hadoop/hdfs-site.xml
        insertafter: "<configuration>"
        block: 
           <property>
           <name>dfs.name.dir</name>
           <value>{{ namedir }}</value>
           </property>


    - name: Configuring core-site.xml file
      blockinfile:
        path: /etc/hadoop/core-site.xml
        insertafter: "<configuration>"
        block:
           <property>
           <name>fs.default.name</name>
           <value>hdfs://{{ nameip }}:9001</value>
           </property>



    - name: Formatting Name Node Directory
      shell: "echo Y | hadoop namenode -format"
      register: format
    - debug:
        var: format
    

    - name: Starting hadoop Name Node services
      shell: "hadoop-daemon.sh start namenode"
      register: service
    - debug:
        var: service
      
    
    - name: Checking status of Name Node Services
      shell: "jps"
      register: jps
    - debug:
        var: jps.stdout_lines
   
